FROM ghcr.io/krism-eu/rakuos-base:minimal-base

LABEL org.opencontainers.image.title="RakuOS KDE Plasma"
LABEL org.opencontainers.image.description="RakuOS KDE Plasma image"
LABEL org.opencontainers.image.source="https://github.com/krism-eu/rakuos-base"

COPY rakuos-kde/build_files /build_files
COPY rakuos-kde/system_files /

RUN chmod +x \
        /build_files/build.sh \
        /build_files/drivers.sh \
        /build_files/post-build-overlay.sh \
        /build_files/validate.sh \
        /usr/bin/rakuos \
        /usr/libexec/rakuos/*

RUN /usr/bin/env bash /build_files/build.sh

RUN /usr/bin/env bash /build_files/post-build-overlay.sh

RUN /usr/bin/env bash /build_files/drivers.sh

RUN /usr/bin/env bash /build_files/validate.sh

RUN systemctl set-default graphical.target

RUN systemctl enable plasmalogin.service

RUN bootc container lint

CMD ["/sbin/init"]
